name = "roll"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
minify = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXTAUTH_URL = "https://fallout76.wiki"
ADMIN_EMAILS = "nathanw0821@gmail.com"
ADMIN_USERNAMES = "ezkialez,test"
ALLOW_PUBLIC_REGISTRATION = "true"
EMAIL_FROM = "R.O.L.L <no-reply@support.fallout76.wiki>"
GOOGLE_CLIENT_ID = "717058834888-tri1suu3o125h1haajjrffufioj75ga7.apps.googleusercontent.com"

[[triggers.crons]]
# Source Check
schedules = ["0 19 * * *"]

[[triggers.crons]]
# Source Sync
schedules = ["20 19 * * *"]
