/**
 * Static combat data for the firepower engine: weapon baselines, id aliases, and
 * boss target dummies. Pure data with no formulas, split out of
 * combat-firepower-engine.ts so the client bundle can tree-shake it separately.
 */

export type WeaponDamageType =
  | "ballistic"
  | "energy"
  | "fire"
  | "cryo"
  | "poison"
  | "radiation"
  | "physical";

export type WeaponClassCategory =
  | "commando"
  | "rifleman"
  | "heavy"
  | "shotgunner"
  | "melee"
  | "unarmed"
  | "gunslinger"
  | "guerrilla"
  | "bow";

export type WeaponCombatBaseStats = {
  id: string;
  label: string;
  maxLevel: 50 | 45;
  baseDamage: number;
  secondaryDamage?: number;
  damageType: WeaponDamageType;
  secondaryDamageType?: WeaponDamageType;
  fireRate: number; // rounds per second (RPS)
  baseVatsApCost: number;
  magazineSize: number;
  weaponClass: WeaponClassCategory;
  isAutomatic: boolean;
  isRanged: boolean;
  isEnergy: boolean;
  isExplosiveInherent?: boolean;
};

/**
 * Authoritative baseline combat stats for Fallout 76 weapons.
 */
export const WEAPON_COMBAT_BASE_CATALOG: Record<string, WeaponCombatBaseStats> = {
  "elders-mark": {
    "id": "elders-mark",
    "label": "Elder's Mark (Submachine Gun · Unique)",
    "maxLevel": 45,
    "baseDamage": 38,
    "damageType": "ballistic",
    "fireRate": 13.5,
    "baseVatsApCost": 18,
    "magazineSize": 50,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "holy-fire": {
    "id": "holy-fire",
    "label": "Holy Fire (Flamer · Unique)",
    "maxLevel": 50,
    "baseDamage": 58,
    "damageType": "fire",
    "fireRate": 9.1,
    "baseVatsApCost": 30,
    "magazineSize": 200,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "anchorage-ace": {
    "id": "anchorage-ace",
    "label": "Anchorage Ace (10mm SMG · Unique)",
    "maxLevel": 50,
    "baseDamage": 36,
    "damageType": "ballistic",
    "fireRate": 10.5,
    "baseVatsApCost": 15,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "cold-shoulder": {
    "id": "cold-shoulder",
    "label": "Cold Shoulder (Double-Barrel · Unique)",
    "maxLevel": 45,
    "baseDamage": 115,
    "secondaryDamage": 75,
    "damageType": "ballistic",
    "secondaryDamageType": "cryo",
    "fireRate": 4,
    "baseVatsApCost": 28,
    "magazineSize": 8,
    "weaponClass": "shotgunner",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "red-terror": {
    "id": "red-terror",
    "label": "Red Terror (LMG · Unique)",
    "maxLevel": 50,
    "baseDamage": 42,
    "damageType": "ballistic",
    "fireRate": 15.9,
    "baseVatsApCost": 35,
    "magazineSize": 150,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "v63-bertha": {
    "id": "v63-bertha",
    "label": "V63 Bertha (Tesla Rifle · Unique)",
    "maxLevel": 50,
    "baseDamage": 78,
    "damageType": "energy",
    "fireRate": 8.3,
    "baseVatsApCost": 28,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "v63-helga": {
    "id": "v63-helga",
    "label": "V63 Helga (Gatling Laser · Unique)",
    "maxLevel": 45,
    "baseDamage": 35,
    "damageType": "energy",
    "fireRate": 18.2,
    "baseVatsApCost": 30,
    "magazineSize": 500,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "v63-olga": {
    "id": "v63-olga",
    "label": "V63 Olga (Laser Rifle · Unique)",
    "maxLevel": 45,
    "baseDamage": 52,
    "damageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 22,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "v63-zweihander": {
    "id": "v63-zweihander",
    "label": "V63 Zweihänder (Super Sledge · Unique)",
    "maxLevel": 50,
    "baseDamage": 125,
    "secondaryDamage": 40,
    "damageType": "physical",
    "secondaryDamageType": "energy",
    "fireRate": 1.2,
    "baseVatsApCost": 35,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "v63-shock-baton": {
    "id": "v63-shock-baton",
    "label": "V63 Shock Baton (Security Baton · Unique)",
    "maxLevel": 45,
    "baseDamage": 65,
    "secondaryDamage": 30,
    "damageType": "physical",
    "secondaryDamageType": "energy",
    "fireRate": 2.2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  // TODO(patch-70): re-derive magazineSize from the new Railway Rifle base capacity (16) once the
  // unique's in-game value is verified; 20 was set against the pre-Patch-70 base of 10.
  "ticket-to-revenge": {
    "id": "ticket-to-revenge",
    "label": "Ticket to Revenge (Railway Rifle · Unique)",
    "maxLevel": 50,
    "baseDamage": 95,
    "damageType": "ballistic",
    "fireRate": 10,
    "baseVatsApCost": 20,
    "magazineSize": 20,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "shattered-grounds": {
    "id": "shattered-grounds",
    "label": "Shattered Grounds (Handmade · Unique)",
    "maxLevel": 45,
    "baseDamage": 45,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 25,
    "magazineSize": 25,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "love-tap": {
    "id": "love-tap",
    "label": "Love Tap (Submachine Gun · Unique)",
    "maxLevel": 45,
    "baseDamage": 40,
    "damageType": "ballistic",
    "fireRate": 10,
    "baseVatsApCost": 22,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "western-spirit": {
    "id": "western-spirit",
    "label": "Western Spirit (Lever Action · Unique)",
    "maxLevel": 45,
    "baseDamage": 85,
    "damageType": "ballistic",
    "fireRate": 2.5,
    "baseVatsApCost": 25,
    "magazineSize": 7,
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "gunthers-big-iron": {
    "id": "gunthers-big-iron",
    "label": "Gunther's Big Iron (Single Action · Unique)",
    "maxLevel": 50,
    "baseDamage": 72,
    "damageType": "ballistic",
    "fireRate": 3.5,
    "baseVatsApCost": 22,
    "magazineSize": 6,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "the-fact-finder": {
    "id": "the-fact-finder",
    "label": "The Fact Finder (.44 Pistol · Unique)",
    "maxLevel": 45,
    "baseDamage": 68,
    "damageType": "ballistic",
    "fireRate": 3,
    "baseVatsApCost": 24,
    "magazineSize": 6,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "the-kabloom": {
    "id": "the-kabloom",
    "label": "The Kabloom (Pump Shotgun · Unique)",
    "maxLevel": 45,
    "baseDamage": 95,
    "secondaryDamage": 40,
    "damageType": "ballistic",
    "secondaryDamageType": "poison",
    "fireRate": 2,
    "baseVatsApCost": 32,
    "magazineSize": 8,
    "weaponClass": "shotgunner",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "grand-finale": {
    "id": "grand-finale",
    "label": "Grand Finale (Broadsider · Unique)",
    "maxLevel": 45,
    "baseDamage": 180,
    "damageType": "ballistic",
    "fireRate": 1,
    "baseVatsApCost": 40,
    "magazineSize": 3,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "boomstick": {
    "id": "boomstick",
    "label": "Boomstick (Missile Launcher · Unique)",
    "maxLevel": 50,
    "baseDamage": 175,
    "damageType": "ballistic",
    "fireRate": 1,
    "baseVatsApCost": 45,
    "magazineSize": 2,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "overkill": {
    "id": "overkill",
    "label": "Overkill (Fat Man · Unique)",
    "maxLevel": 45,
    "baseDamage": 460,
    "damageType": "ballistic",
    "fireRate": 0.5,
    "baseVatsApCost": 65,
    "magazineSize": 1,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "sole-survivor": {
    "id": "sole-survivor",
    "label": "Sole Survivor (Lever Action · Unique)",
    "maxLevel": 45,
    "baseDamage": 75,
    "damageType": "ballistic",
    "fireRate": 2.5,
    "baseVatsApCost": 25,
    "magazineSize": 5,
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "face-breaker": {
    "id": "face-breaker",
    "label": "Face Breaker (Power Fist · Unique)",
    "maxLevel": 50,
    "baseDamage": 65,
    "damageType": "physical",
    "fireRate": 1.8,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "unstoppable-monster": {
    "id": "unstoppable-monster",
    "label": "Unstoppable Monster (Deathclaw Gauntlet · Unique)",
    "maxLevel": 50,
    "baseDamage": 62,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "the-gutter": {
    "id": "the-gutter",
    "label": "The Gutter (Chinese Officer Sword · Unique)",
    "maxLevel": 45,
    "baseDamage": 52,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 22,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "whacker-smacker": {
    "id": "whacker-smacker",
    "label": "Whacker Smacker (Super Sledge · Unique)",
    "maxLevel": 50,
    "baseDamage": 110,
    "damageType": "physical",
    "fireRate": 1.3,
    "baseVatsApCost": 35,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "crowd-control": {
    "id": "crowd-control",
    "label": "Crowd Control (Combat Shotgun · Unique)",
    "maxLevel": 50,
    "baseDamage": 90,
    "damageType": "ballistic",
    "fireRate": 3.5,
    "baseVatsApCost": 26,
    "magazineSize": 8,
    "weaponClass": "shotgunner",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "medical-malpractice": {
    "id": "medical-malpractice",
    "label": "Medical Malpractice (.44 Pistol · Unique)",
    "maxLevel": 45,
    "baseDamage": 60,
    "damageType": "ballistic",
    "fireRate": 3,
    "baseVatsApCost": 22,
    "magazineSize": 6,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "mechanics-best-friend": {
    "id": "mechanics-best-friend",
    "label": "Mechanic's Best Friend (Pipe Wrench · Unique)",
    "maxLevel": 50,
    "baseDamage": 45,
    "damageType": "physical",
    "fireRate": 1.8,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "the-action-hero": {
    "id": "the-action-hero",
    "label": "The Action Hero (.50 Cal · Unique)",
    "maxLevel": 45,
    "baseDamage": 42,
    "damageType": "ballistic",
    "fireRate": 11.4,
    "baseVatsApCost": 30,
    "magazineSize": 250,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "resolute-veteran": {
    "id": "resolute-veteran",
    "label": "Resolute Veteran (Gatling Gun · Unique)",
    "maxLevel": 50,
    "baseDamage": 86,
    "damageType": "ballistic",
    "fireRate": 4,
    "baseVatsApCost": 28,
    "magazineSize": 250,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "night-light": {
    "id": "night-light",
    "label": "Night Light (Tesla Rifle · Unique)",
    "maxLevel": 50,
    "baseDamage": 78,
    "damageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 28,
    "magazineSize": 15,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "doctors-orders": {
    "id": "doctors-orders",
    "label": "Doctor's Orders (Hunting Rifle · Unique)",
    "maxLevel": 50,
    "baseDamage": 80,
    "damageType": "ballistic",
    "fireRate": 1.2,
    "baseVatsApCost": 32,
    "magazineSize": 5,
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "fixer": {
    "id": "fixer",
    "label": "The Fixer",
    "maxLevel": 50,
    "baseDamage": 48,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 25,
    "magazineSize": 25,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "the-fixer": {
    "id": "the-fixer",
    "label": "The Fixer",
    "maxLevel": 50,
    "baseDamage": 48,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 25,
    "magazineSize": 25,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "handmade": {
    "id": "handmade",
    "label": "Handmade Rifle",
    "maxLevel": 45,
    "baseDamage": 45,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 25,
    "magazineSize": 25,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "handmade-rifle": {
    "id": "handmade-rifle",
    "label": "Handmade Rifle",
    "maxLevel": 45,
    "baseDamage": 45,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 25,
    "magazineSize": 25,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "railway": {
    "id": "railway",
    "label": "Railway Rifle",
    "maxLevel": 50,
    "baseDamage": 95,
    "damageType": "ballistic",
    "fireRate": 10,
    "baseVatsApCost": 20,
    "magazineSize": 16, // Patch 70 "The Slasher" (2026-09-15): base ammo capacity 10 -> 16; semi-auto fire delay reduced; spike weight 0.2 -> 0.15
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "railway-rifle": {
    "id": "railway-rifle",
    "label": "Railway Rifle",
    "maxLevel": 50,
    "baseDamage": 95,
    "damageType": "ballistic",
    "fireRate": 10,
    "baseVatsApCost": 20,
    "magazineSize": 16, // Patch 70 "The Slasher" (2026-09-15): base ammo capacity 10 -> 16; semi-auto fire delay reduced; spike weight 0.2 -> 0.15
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "combat-rifle": {
    "id": "combat-rifle",
    "label": "Combat Rifle",
    "maxLevel": 50,
    "baseDamage": 40,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 25,
    "magazineSize": 20,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "assault-rifle": {
    "id": "assault-rifle",
    "label": "Assault Rifle",
    "maxLevel": 50,
    "baseDamage": 36,
    "damageType": "ballistic",
    "fireRate": 10,
    "baseVatsApCost": 22,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "hunting-rifle": {
    "id": "hunting-rifle",
    "label": "Hunting Rifle / Sniper",
    "maxLevel": 50,
    "baseDamage": 70,
    "damageType": "ballistic",
    "fireRate": 1.2,
    "baseVatsApCost": 32,
    "magazineSize": 5,
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "lever-action": {
    "id": "lever-action",
    "label": "Lever Action Rifle",
    "maxLevel": 45,
    "baseDamage": 75,
    "damageType": "ballistic",
    "fireRate": 2.5,
    "baseVatsApCost": 25,
    "magazineSize": 6, // Patch 70: lever action clip 5 -> 6
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "gauss-rifle": {
    "id": "gauss-rifle",
    "label": "Gauss Rifle",
    "maxLevel": 45,
    "baseDamage": 140,
    "damageType": "energy",
    "fireRate": 2,
    "baseVatsApCost": 28,
    "magazineSize": 5,
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": true,
    "isExplosiveInherent": true
  },
  "radium-rifle": {
    "id": "radium-rifle",
    "label": "Radium Rifle",
    "maxLevel": 50,
    "baseDamage": 38,
    "secondaryDamage": 15,
    "damageType": "ballistic",
    "secondaryDamageType": "radiation",
    "fireRate": 9.1,
    "baseVatsApCost": 24,
    "magazineSize": 20,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "submachine-gun": {
    "id": "submachine-gun",
    "label": "Submachine Gun (.45)",
    "maxLevel": 45,
    "baseDamage": 34,
    "damageType": "ballistic",
    "fireRate": 10,
    "baseVatsApCost": 24,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "10mm-smg": {
    "id": "10mm-smg",
    "label": "10mm Submachine Gun",
    "maxLevel": 50,
    "baseDamage": 33,
    "damageType": "ballistic",
    "fireRate": 10.5,
    "baseVatsApCost": 22,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "pipe-gun": {
    "id": "pipe-gun",
    "label": "Pipe Gun / Bolt-Action",
    "maxLevel": 50,
    "baseDamage": 26,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 18,
    "magazineSize": 18,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "cremator": {
    "id": "cremator",
    "label": "Cremator",
    "maxLevel": 50,
    "baseDamage": 80,
    "secondaryDamage": 140,
    "damageType": "fire",
    "secondaryDamageType": "fire",
    "fireRate": 1.5,
    "baseVatsApCost": 35,
    "magazineSize": 12,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": true,
    "isExplosiveInherent": true
  },
  "flamer": {
    "id": "flamer",
    "label": "Flamer",
    "maxLevel": 50,
    "baseDamage": 52,
    "damageType": "fire",
    "fireRate": 9.1,
    "baseVatsApCost": 30,
    "magazineSize": 100,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "gatling-plasma": {
    "id": "gatling-plasma",
    "label": "Gatling Plasma",
    "maxLevel": 50,
    "baseDamage": 58,
    "secondaryDamage": 58,
    "damageType": "ballistic",
    "secondaryDamageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 30,
    "magazineSize": 250,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "gatling-laser": {
    "id": "gatling-laser",
    "label": "Gatling Laser / Ultracite",
    "maxLevel": 45,
    "baseDamage": 32,
    "damageType": "energy",
    "fireRate": 18.2,
    "baseVatsApCost": 30,
    "magazineSize": 500,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "plasma-caster": {
    "id": "plasma-caster",
    "label": "Plasma Caster",
    "maxLevel": 50,
    "baseDamage": 76,
    "secondaryDamage": 76,
    "damageType": "ballistic",
    "secondaryDamageType": "energy",
    "fireRate": 3.3,
    "baseVatsApCost": 30,
    "magazineSize": 20,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": true
  },
  "gauss-minigun": {
    "id": "gauss-minigun",
    "label": "Gauss Minigun",
    "maxLevel": 45,
    "baseDamage": 45,
    "secondaryDamage": 15,
    "damageType": "energy",
    "secondaryDamageType": "energy",
    "fireRate": 15,
    "baseVatsApCost": 35,
    "magazineSize": 500,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true,
    "isExplosiveInherent": true
  },
  "minigun": {
    "id": "minigun",
    "label": "Minigun",
    "maxLevel": 45,
    "baseDamage": 24,
    "damageType": "ballistic",
    "fireRate": 20,
    "baseVatsApCost": 35,
    "magazineSize": 500,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "cal50": {
    "id": "cal50",
    "label": ".50 Cal Machine Gun",
    "maxLevel": 45,
    "baseDamage": 42,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 30,
    "magazineSize": 250,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "50-cal-machine-gun": {
    "id": "50-cal-machine-gun",
    "label": ".50 Cal Machine Gun",
    "maxLevel": 45,
    "baseDamage": 42,
    "damageType": "ballistic",
    "fireRate": 9.1,
    "baseVatsApCost": 30,
    "magazineSize": 250,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "lmg": {
    "id": "lmg",
    "label": "Light Machine Gun (LMG)",
    "maxLevel": 50,
    "baseDamage": 42,
    "damageType": "ballistic",
    "fireRate": 15.9,
    "baseVatsApCost": 35,
    "magazineSize": 75,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "gatling-gun": {
    "id": "gatling-gun",
    "label": "Gatling Gun (5mm)",
    "maxLevel": 50,
    "baseDamage": 86,
    "damageType": "ballistic",
    "fireRate": 4,
    "baseVatsApCost": 28,
    "magazineSize": 250,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "pepper-shaker": {
    "id": "pepper-shaker",
    "label": "Pepper Shaker",
    "maxLevel": 50,
    "baseDamage": 60,
    "damageType": "ballistic",
    "fireRate": 8,
    "baseVatsApCost": 30,
    "magazineSize": 50,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false
  },
  "harpoon-gun": {
    "id": "harpoon-gun",
    "label": "Harpoon Gun",
    "maxLevel": 50,
    "baseDamage": 150,
    "damageType": "ballistic",
    "fireRate": 1,
    "baseVatsApCost": 35,
    "magazineSize": 1,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "broadsider": {
    "id": "broadsider",
    "label": "Broadsider",
    "maxLevel": 45,
    "baseDamage": 165,
    "damageType": "ballistic",
    "fireRate": 1,
    "baseVatsApCost": 40,
    "magazineSize": 1,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "missile-launcher": {
    "id": "missile-launcher",
    "label": "Missile Launcher",
    "maxLevel": 50,
    "baseDamage": 160,
    "damageType": "ballistic",
    "fireRate": 1,
    "baseVatsApCost": 45,
    "magazineSize": 1,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "fat-man": {
    "id": "fat-man",
    "label": "Fat Man / Mini Nuke",
    "maxLevel": 45,
    "baseDamage": 460,
    "damageType": "ballistic",
    "fireRate": 0.5,
    "baseVatsApCost": 65,
    "magazineSize": 1,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "auto-grenade-launcher": {
    "id": "auto-grenade-launcher",
    "label": "Auto Grenade Launcher",
    "maxLevel": 50,
    "baseDamage": 120,
    "damageType": "ballistic",
    "fireRate": 3,
    "baseVatsApCost": 40,
    "magazineSize": 12,
    "weaponClass": "heavy",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "m79-grenade": {
    "id": "m79-grenade",
    "label": "M79 Grenade Launcher",
    "maxLevel": 45,
    "baseDamage": 110,
    "damageType": "ballistic",
    "fireRate": 1,
    "baseVatsApCost": 35,
    "magazineSize": 1,
    "weaponClass": "heavy",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false,
    "isExplosiveInherent": true
  },
  "alien-disintegrator": {
    "id": "alien-disintegrator",
    "label": "Alien Disintegrator",
    "maxLevel": 50,
    "baseDamage": 46,
    "damageType": "energy",
    "fireRate": 7.5,
    "baseVatsApCost": 20,
    "magazineSize": 20,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "enclave-plasma": {
    "id": "enclave-plasma",
    "label": "Enclave Plasma Gun",
    "maxLevel": 45,
    "baseDamage": 48,
    "secondaryDamage": 48,
    "damageType": "ballistic",
    "secondaryDamageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 28,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "enclave-plasma-rifle": {
    "id": "enclave-plasma-rifle",
    "label": "Enclave Plasma Rifle",
    "maxLevel": 45,
    "baseDamage": 48,
    "secondaryDamage": 48,
    "damageType": "ballistic",
    "secondaryDamageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 28,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "plasma-flamer": {
    "id": "plasma-flamer",
    "label": "Plasma Flamer",
    "maxLevel": 45,
    "baseDamage": 45,
    "secondaryDamage": 45,
    "damageType": "ballistic",
    "secondaryDamageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 28,
    "magazineSize": 300,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "plasma-gun": {
    "id": "plasma-gun",
    "label": "Plasma Gun",
    "maxLevel": 45,
    "baseDamage": 42,
    "secondaryDamage": 42,
    "damageType": "ballistic",
    "secondaryDamageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 26,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "laser-rifle": {
    "id": "laser-rifle",
    "label": "Laser Rifle / Pistol",
    "maxLevel": 45,
    "baseDamage": 45,
    "damageType": "energy",
    "fireRate": 9.1,
    "baseVatsApCost": 22,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "ultracite-laser": {
    "id": "ultracite-laser",
    "label": "Ultracite Laser Rifle",
    "maxLevel": 50,
    "baseDamage": 40,
    "damageType": "energy",
    "fireRate": 10.5,
    "baseVatsApCost": 22,
    "magazineSize": 30,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "tesla": {
    "id": "tesla",
    "label": "Tesla Rifle",
    "maxLevel": 50,
    "baseDamage": 78,
    "damageType": "energy",
    "fireRate": 8.3,
    "baseVatsApCost": 28,
    "magazineSize": 15,
    "weaponClass": "commando",
    "isAutomatic": true,
    "isRanged": true,
    "isEnergy": true
  },
  "gamma-gun": {
    "id": "gamma-gun",
    "label": "Gamma Gun",
    "maxLevel": 45,
    "baseDamage": 110,
    "secondaryDamage": 60,
    "damageType": "radiation",
    "secondaryDamageType": "energy",
    "fireRate": 3.5,
    "baseVatsApCost": 24,
    "magazineSize": 8,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": true
  },
  "alien-blaster": {
    "id": "alien-blaster",
    "label": "Alien Blaster",
    "maxLevel": 50,
    "baseDamage": 32,
    "damageType": "energy",
    "fireRate": 6,
    "baseVatsApCost": 15,
    "magazineSize": 42,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": true
  },
  "laser-musket": {
    "id": "laser-musket",
    "label": "Laser Musket",
    "maxLevel": 50,
    "baseDamage": 65,
    "damageType": "energy",
    "fireRate": 1.5,
    "baseVatsApCost": 28,
    "magazineSize": 6,
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": true
  },
  "gauss-shotgun": {
    "id": "gauss-shotgun",
    "label": "Gauss Shotgun",
    "maxLevel": 50,
    "baseDamage": 140,
    "damageType": "energy",
    "fireRate": 2.5,
    "baseVatsApCost": 25,
    "magazineSize": 8,
    "weaponClass": "shotgunner",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": true,
    "isExplosiveInherent": true
  },
  "combat-shotgun": {
    "id": "combat-shotgun",
    "label": "Combat Shotgun",
    "maxLevel": 50,
    "baseDamage": 90,
    "damageType": "ballistic",
    "fireRate": 3.5,
    "baseVatsApCost": 26,
    "magazineSize": 8,
    "weaponClass": "shotgunner",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "pump-shotgun": {
    "id": "pump-shotgun",
    "label": "Pump Action Shotgun",
    "maxLevel": 45,
    "baseDamage": 95,
    "damageType": "ballistic",
    "fireRate": 2,
    "baseVatsApCost": 32,
    "magazineSize": 8,
    "weaponClass": "shotgunner",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "double-barrel": {
    "id": "double-barrel",
    "label": "Double-Barrel Shotgun",
    "maxLevel": 45,
    "baseDamage": 115,
    "damageType": "ballistic",
    "fireRate": 4,
    "baseVatsApCost": 28,
    "magazineSize": 2,
    "weaponClass": "shotgunner",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "crusader-pistol": {
    "id": "crusader-pistol",
    "label": "Crusader Pistol",
    "maxLevel": 50,
    "baseDamage": 45,
    "damageType": "ballistic",
    "fireRate": 4.5,
    "baseVatsApCost": 18,
    "magazineSize": 12,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "10mm-pistol": {
    "id": "10mm-pistol",
    "label": "10mm Pistol",
    "maxLevel": 45,
    "baseDamage": 31,
    "damageType": "ballistic",
    "fireRate": 6,
    "baseVatsApCost": 16,
    "magazineSize": 12,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "western-revolver": {
    "id": "western-revolver",
    "label": "Western Revolver",
    "maxLevel": 50,
    "baseDamage": 72,
    "damageType": "ballistic",
    "fireRate": 3,
    "baseVatsApCost": 22,
    "magazineSize": 6,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "44-pistol": {
    "id": "44-pistol",
    "label": ".44 Pistol",
    "maxLevel": 45,
    "baseDamage": 60,
    "damageType": "ballistic",
    "fireRate": 3,
    "baseVatsApCost": 24,
    "magazineSize": 6,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "single-action": {
    "id": "single-action",
    "label": "Single Action Revolver",
    "maxLevel": 50,
    "baseDamage": 68,
    "damageType": "ballistic",
    "fireRate": 3,
    "baseVatsApCost": 22,
    "magazineSize": 6,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "black-powder-pistol": {
    "id": "black-powder-pistol",
    "label": "Black Powder Pistol / Rifle",
    "maxLevel": 50,
    "baseDamage": 160,
    "damageType": "ballistic",
    "fireRate": 0.8,
    "baseVatsApCost": 28,
    "magazineSize": 1,
    "weaponClass": "gunslinger",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "the-dragon": {
    "id": "the-dragon",
    "label": "The Dragon",
    "maxLevel": 45,
    "baseDamage": 225,
    "damageType": "ballistic",
    "fireRate": 0.5,
    "baseVatsApCost": 35,
    "magazineSize": 4,
    "weaponClass": "rifleman",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "compound-bow": {
    "id": "compound-bow",
    "label": "Compound Bow",
    "maxLevel": 50,
    "baseDamage": 110,
    "damageType": "physical",
    "fireRate": 0.8,
    "baseVatsApCost": 22,
    "magazineSize": 1,
    "weaponClass": "bow",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "bow": {
    "id": "bow",
    "label": "Hunting Bow",
    "maxLevel": 50,
    "baseDamage": 90,
    "damageType": "physical",
    "fireRate": 1,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "bow",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "crossbow": {
    "id": "crossbow",
    "label": "Crossbow",
    "maxLevel": 45,
    "baseDamage": 85,
    "damageType": "physical",
    "fireRate": 1.2,
    "baseVatsApCost": 24,
    "magazineSize": 1,
    "weaponClass": "bow",
    "isAutomatic": false,
    "isRanged": true,
    "isEnergy": false
  },
  "chainsaw": {
    "id": "chainsaw",
    "label": "Chainsaw",
    "maxLevel": 50,
    "baseDamage": 38,
    "damageType": "physical",
    "fireRate": 8,
    "baseVatsApCost": 15,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": true,
    "isRanged": false,
    "isEnergy": false
  },
  "auto-axe": {
    "id": "auto-axe",
    "label": "Auto Axe",
    "maxLevel": 50,
    "baseDamage": 42,
    "damageType": "physical",
    "fireRate": 8,
    "baseVatsApCost": 15,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": true,
    "isRanged": false,
    "isEnergy": false
  },
  "mr-handy-buzz-blade": {
    "id": "mr-handy-buzz-blade",
    "label": "Mr. Handy Buzz Blade",
    "maxLevel": 45,
    "baseDamage": 18,
    "damageType": "physical",
    "fireRate": 8,
    "baseVatsApCost": 15,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": true,
    "isRanged": false,
    "isEnergy": false
  },
  "drill": {
    "id": "drill",
    "label": "Drill",
    "maxLevel": 50,
    "baseDamage": 14,
    "damageType": "physical",
    "fireRate": 8,
    "baseVatsApCost": 15,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": true,
    "isRanged": false,
    "isEnergy": false
  },
  "ripper": {
    "id": "ripper",
    "label": "The Ripper",
    "maxLevel": 50,
    "baseDamage": 22,
    "damageType": "physical",
    "fireRate": 8,
    "baseVatsApCost": 15,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": true,
    "isRanged": false,
    "isEnergy": false
  },
  "power-fist": {
    "id": "power-fist",
    "label": "Power Fist",
    "maxLevel": 50,
    "baseDamage": 58,
    "damageType": "physical",
    "fireRate": 1.8,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "dc-gauntlet": {
    "id": "dc-gauntlet",
    "label": "Deathclaw Gauntlet",
    "maxLevel": 50,
    "baseDamage": 55,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "deathclaw-gauntlet": {
    "id": "deathclaw-gauntlet",
    "label": "Deathclaw Gauntlet",
    "maxLevel": 50,
    "baseDamage": 55,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "gauntlet": {
    "id": "gauntlet",
    "label": "Gauntlet (Settlers)",
    "maxLevel": 50,
    "baseDamage": 56,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "bear-arm": {
    "id": "bear-arm",
    "label": "Bear Arm",
    "maxLevel": 50,
    "baseDamage": 54,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "meat-hook": {
    "id": "meat-hook",
    "label": "Meat Hook",
    "maxLevel": 45,
    "baseDamage": 45,
    "damageType": "physical",
    "fireRate": 2.2,
    "baseVatsApCost": 18,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "mole-miner-gauntlet": {
    "id": "mole-miner-gauntlet",
    "label": "Mole Miner Gauntlet",
    "maxLevel": 50,
    "baseDamage": 50,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "boxing-glove": {
    "id": "boxing-glove",
    "label": "Boxing Glove",
    "maxLevel": 45,
    "baseDamage": 38,
    "damageType": "physical",
    "fireRate": 2.5,
    "baseVatsApCost": 18,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "knuckles": {
    "id": "knuckles",
    "label": "Knuckles",
    "maxLevel": 50,
    "baseDamage": 32,
    "damageType": "physical",
    "fireRate": 2.8,
    "baseVatsApCost": 16,
    "magazineSize": 1,
    "weaponClass": "unarmed",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "war-glaive": {
    "id": "war-glaive",
    "label": "War Glaive",
    "maxLevel": 50,
    "baseDamage": 92,
    "damageType": "physical",
    "fireRate": 1.4,
    "baseVatsApCost": 30,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "plasma-cutter": {
    "id": "plasma-cutter",
    "label": "Plasma Cutter",
    "maxLevel": 50,
    "baseDamage": 50,
    "secondaryDamage": 35,
    "damageType": "physical",
    "secondaryDamageType": "energy",
    "fireRate": 2.2,
    "baseVatsApCost": 22,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": true
  },
  "super-sledge": {
    "id": "super-sledge",
    "label": "Super Sledge",
    "maxLevel": 50,
    "baseDamage": 105,
    "damageType": "physical",
    "fireRate": 1.2,
    "baseVatsApCost": 35,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "sledgehammer": {
    "id": "sledgehammer",
    "label": "Sledgehammer",
    "maxLevel": 50,
    "baseDamage": 85,
    "damageType": "physical",
    "fireRate": 1.2,
    "baseVatsApCost": 32,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "grognak-axe": {
    "id": "grognak-axe",
    "label": "Grognak's Axe",
    "maxLevel": 50,
    "baseDamage": 95,
    "damageType": "physical",
    "fireRate": 1.3,
    "baseVatsApCost": 32,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "fire-axe": {
    "id": "fire-axe",
    "label": "Fire Axe",
    "maxLevel": 45,
    "baseDamage": 82,
    "damageType": "physical",
    "fireRate": 1.3,
    "baseVatsApCost": 30,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "tenderizer": {
    "id": "tenderizer",
    "label": "The Tenderizer",
    "maxLevel": 50,
    "baseDamage": 100,
    "damageType": "physical",
    "fireRate": 1.2,
    "baseVatsApCost": 35,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "sheepsquatch-staff": {
    "id": "sheepsquatch-staff",
    "label": "Sheepsquatch Staff",
    "maxLevel": 50,
    "baseDamage": 88,
    "damageType": "physical",
    "fireRate": 1.3,
    "baseVatsApCost": 30,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "sheepsquatch-club": {
    "id": "sheepsquatch-club",
    "label": "Sheepsquatch Club",
    "maxLevel": 50,
    "baseDamage": 60,
    "damageType": "physical",
    "fireRate": 2,
    "baseVatsApCost": 24,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "baseball-bat": {
    "id": "baseball-bat",
    "label": "Baseball Bat",
    "maxLevel": 45,
    "baseDamage": 62,
    "damageType": "physical",
    "fireRate": 1.8,
    "baseVatsApCost": 26,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "combat-knife": {
    "id": "combat-knife",
    "label": "Combat Knife / Bowie",
    "maxLevel": 50,
    "baseDamage": 32,
    "damageType": "physical",
    "fireRate": 3.5,
    "baseVatsApCost": 15,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "switchblade": {
    "id": "switchblade",
    "label": "Switchblade",
    "maxLevel": 50,
    "baseDamage": 26,
    "damageType": "physical",
    "fireRate": 3.8,
    "baseVatsApCost": 14,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "pipe-wrench": {
    "id": "pipe-wrench",
    "label": "Pipe Wrench",
    "maxLevel": 50,
    "baseDamage": 35,
    "damageType": "physical",
    "fireRate": 1.8,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "shishkebab": {
    "id": "shishkebab",
    "label": "Shishkebab",
    "maxLevel": 45,
    "baseDamage": 45,
    "secondaryDamage": 30,
    "damageType": "physical",
    "secondaryDamageType": "fire",
    "fireRate": 2.2,
    "baseVatsApCost": 24,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "cultist-dagger": {
    "id": "cultist-dagger",
    "label": "Cultist Dagger / Blade",
    "maxLevel": 45,
    "baseDamage": 30,
    "damageType": "physical",
    "fireRate": 3.5,
    "baseVatsApCost": 15,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": false
  },
  "cattleprod": {
    "id": "cattleprod",
    "label": "Cattle Prod",
    "maxLevel": 50,
    "baseDamage": 42,
    "secondaryDamage": 25,
    "damageType": "physical",
    "secondaryDamageType": "energy",
    "fireRate": 2.2,
    "baseVatsApCost": 20,
    "magazineSize": 1,
    "weaponClass": "melee",
    "isAutomatic": false,
    "isRanged": false,
    "isEnergy": true
  }
};

export const WEAPON_ALIASES: Record<string, string> = {
  "the-fixer": "fixer",
  "handmade-rifle": "handmade",
  "railway-rifle": "railway",
  "50-cal-machine-gun": "cal50",
  "enclave-plasma-rifle": "enclave-plasma",
  "deathclaw-gauntlet": "dc-gauntlet",
};

export type BossTargetDummy = {
  id: string;
  name: string;
  shortName: string;
  category: "boss" | "standard" | "sheet";
  damageResistance: number;
  energyResistance: number;
  flatDamageReductionPct: number; // e.g. 0.70 for Queen (70% flat reduction)
  description: string;
};

export const TARGET_DUMMY_CATALOG: Record<string, BossTargetDummy> = {
  "scorchbeast-queen": {
    id: "scorchbeast-queen",
    name: "Scorchbeast Queen",
    shortName: "SBQ",
    category: "boss",
    damageResistance: 300,
    energyResistance: 300,
    flatDamageReductionPct: 0.70,
    description: "Endgame Nuke Boss (300 DR, 70% flat damage reduction)",
  },
  "earle-williams": {
    id: "earle-williams",
    name: "Earle Williams (Colossal Problem)",
    shortName: "Earle",
    category: "boss",
    damageResistance: 400,
    energyResistance: 400,
    flatDamageReductionPct: 0.80,
    description: "Deep Mine Colossus Boss (400 DR, 80% flat damage reduction)",
  },
  "ultracite-titan": {
    id: "ultracite-titan",
    name: "Ultracite Titan (Seismic Activity)",
    shortName: "Titan",
    category: "boss",
    damageResistance: 350,
    energyResistance: 350,
    flatDamageReductionPct: 0.75,
    description: "Ash Heap Behemoth Boss (350 DR, 75% flat damage reduction)",
  },
  "level-100-super-mutant": {
    id: "level-100-super-mutant",
    name: "Level 100 Super Mutant Behemoth",
    shortName: "Mutant L100",
    category: "standard",
    damageResistance: 210,
    energyResistance: 210,
    flatDamageReductionPct: 0.0,
    description: "High-tier Appalachian standard target (210 DR, 0% flat reduction)",
  },
  "raw-unarmored": {
    id: "raw-unarmored",
    name: "Unarmored / Raw Sheet DPS",
    shortName: "Raw Sheet",
    category: "sheet",
    damageResistance: 0,
    energyResistance: 0,
    flatDamageReductionPct: 0.0,
    description: "Unmitigated baseline benchmark dummy (0 DR, 0% reduction)",
  },
};

export const TARGET_DUMMY_LIST: BossTargetDummy[] = Object.values(TARGET_DUMMY_CATALOG);
